package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func mdEscape(s string) string {
	return strings.NewReplacer("|", "\\|", "\n", " ", "<", "&lt;", ">", "&gt;").Replace(s)
}

func counts(ops []Operation, pred func(Operation) bool) map[string]int {
	c := map[string]int{}
	for _, o := range ops {
		if pred(o) {
			c[o.Disposition]++
			c["total"]++
		}
	}
	return c
}

func writeFile(dir, name string, b *strings.Builder) {
	if err := os.WriteFile(filepath.Join(dir, name), []byte(b.String()), 0o644); err != nil {
		fail("%v", err)
	}
}

const generatedNote = "<!-- Generated by cmd/trimble-catalog from the official OpenAPI definitions. Do not edit by hand; run `make catalog`. -->\n\n"

func writeDocs(dir string, cat *Catalog) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		fail("%v", err)
	}
	var b strings.Builder
	b.WriteString(generatedNote)
	b.WriteString("# Trimble API endpoint coverage\n\n")
	fmt.Fprintf(&b, "Every operation in every API definition that Trimble publishes in its official SwaggerHub organisation (%s) is listed here with exactly one disposition. The definitions were retrieved on %s. `internal/catalog` tests fail if any operation lacks a disposition.\n\n", cat.Index, cat.Retrieved)
	b.WriteString("| Disposition | Meaning | MCP tool |\n|---|---|---|\n")
	b.WriteString("| `read` | Production read; executed against the documented regional host | `trimble_api_read`, or a typed tool where listed |\n")
	b.WriteString("| `plan` | Production change (POST, PUT, PATCH or DELETE); validated and returned as a dry-run request plan, never executed | `trimble_api_plan` |\n")
	b.WriteString("| `variant` | The same method and path as a production operation in a staging, integration, QA, test or draft copy | Covered by the production operation named in `covered_by` |\n")
	b.WriteString("| `excluded` | Not callable by the bridge; the reason is recorded per operation | none |\n\n")

	all := counts(cat.Operations, func(Operation) bool { return true })
	fmt.Fprintf(&b, "**Totals:** %d operations; %d read, %d plan, %d variant, %d excluded.\n\n", all["total"], all["read"], all["plan"], all["variant"], all["excluded"])

	b.WriteString("## Production APIs\n\n| API | Status | Definition | Regions | Operations | read | plan | excluded | Reference |\n|---|---|---|---|---|---|---|---|---|\n")
	for _, a := range cat.APIs {
		c := counts(cat.Operations, func(o Operation) bool { return o.Source == a.Source })
		fmt.Fprintf(&b, "| %s | %s | [%s](%s) | %s | %d | %d | %d | %d | [%s.md](%s.md) |\n",
			a.Title, a.Status, a.Source, srcURLOf(cat, a.Source), strings.Join(a.Regions, ", "), c["total"], c["read"], c["plan"], c["excluded"], a.ID, a.ID)
	}
	b.WriteString("\n## All published definitions\n\n| Definition | Title | Class | Variant of | Operations | Note |\n|---|---|---|---|---|---|\n")
	for _, s := range cat.Sources {
		fmt.Fprintf(&b, "| [%s](%s) | %s | %s | %s | %d | %s |\n", s.ID, s.URL, mdEscape(s.Title), s.Class, s.VariantOf, s.Ops, mdEscape(s.Note))
	}
	b.WriteString("\nNon-production operations are accounted for in [non-production.md](non-production.md).\n\n")
	b.WriteString("## Hosts\n\nBase URLs are taken from each definition's `servers` block and cross-checked against `GET https://app.connect.trimble.com/tc/api/2.0/regions`. Core API paths that do not start with `/2.x/` are served under `/tc/api/2.0`.\n\n")
	for _, a := range cat.APIs {
		fmt.Fprintf(&b, "- **%s**:", a.ID)
		for _, env := range []string{"production", "stage"} {
			hs := a.Hosts[env]
			if len(hs) == 0 {
				continue
			}
			var rs []string
			for r := range hs {
				rs = append(rs, r)
			}
			sort.Strings(rs)
			var parts []string
			for _, r := range rs {
				parts = append(parts, r+" `"+hs[r]+"`")
			}
			fmt.Fprintf(&b, " %s: %s.", env, strings.Join(parts, ", "))
		}
		b.WriteString("\n")
	}
	writeFile(dir, "README.md", &b)

	for _, a := range cat.APIs {
		var p strings.Builder
		p.WriteString(generatedNote)
		fmt.Fprintf(&p, "# %s\n\n", a.Title)
		fmt.Fprintf(&p, "- **Definition:** [%s](%s), status %s. Security schemes: %s.\n", a.Source, srcURLOf(cat, a.Source), a.Status, strings.Join(a.Security, ", "))
		fmt.Fprintf(&p, "- **Regions:** %s.\n", strings.Join(a.Regions, ", "))
		p.WriteString("- **Calling from the MCP:** pass `api: \"" + a.ID + "\"` and the operation `key` shown below to `trimble_api_read` (read) or `trimble_api_plan` (plan). Path and query parameters are validated against this catalogue.\n\n")
		byTag := map[string][]Operation{}
		var tags []string
		for _, o := range cat.Operations {
			if o.Source != a.Source {
				continue
			}
			t := "Untagged"
			if len(o.Tags) > 0 {
				t = o.Tags[0]
			}
			if byTag[t] == nil {
				tags = append(tags, t)
			}
			byTag[t] = append(byTag[t], o)
		}
		sort.Strings(tags)
		for _, t := range tags {
			fmt.Fprintf(&p, "## %s\n\n| Method | Path | Disposition | Summary | Parameters |\n|---|---|---|---|---|\n", mdEscape(t))
			for _, o := range byTag[t] {
				disp := "`" + o.Disposition + "`"
				if o.Tool != "" {
					disp += " (also `" + o.Tool + "`)"
				}
				if o.Disposition == "excluded" {
					disp += ": " + mdEscape(o.Reason)
				}
				var ps []string
				for _, pr := range o.Params {
					req := ""
					if pr.Required {
						req = "*"
					}
					ps = append(ps, fmt.Sprintf("%s%s (%s)", pr.Name, req, pr.In))
				}
				if len(o.BodyTypes) > 0 {
					ps = append(ps, "body: "+strings.Join(o.BodyTypes, ", "))
				}
				summary := mdEscape(o.Summary)
				if o.Deprecated {
					summary = "**Deprecated.** " + summary
				}
				fmt.Fprintf(&p, "| `%s` | `%s` | %s | %s | %s |\n", o.Method, o.Path, disp, summary, mdEscape(strings.Join(ps, "; ")))
			}
			p.WriteString("\n")
		}
		p.WriteString("`*` marks a required parameter.\n")
		writeFile(dir, a.ID+".md", &p)
	}

	var n strings.Builder
	n.WriteString(generatedNote)
	n.WriteString("# Non-production operations\n\nEvery operation in a staging, integration, QA, test, draft, internal or empty definition. `variant` operations are the same call as the production operation they name. `excluded` operations exist only outside production or in Trimble-internal APIs and are never called.\n\n")
	for _, s := range cat.Sources {
		if s.Class == "production" {
			continue
		}
		fmt.Fprintf(&n, "## %s (%s)\n\n%s. %d operations.\n\n", s.ID, s.Class, mdEscape(firstNonEmpty(s.Note, s.Title)), s.Ops)
		if s.Ops == 0 {
			continue
		}
		n.WriteString("| Method | Path | Disposition | Detail |\n|---|---|---|---|\n")
		for _, o := range cat.Operations {
			if o.Source != s.ID {
				continue
			}
			detail := o.Reason
			if o.CoveredBy != "" {
				detail = "covered by `" + o.CoveredBy + "`"
			}
			fmt.Fprintf(&n, "| `%s` | `%s` | `%s` | %s |\n", o.Method, o.Path, o.Disposition, mdEscape(detail))
		}
		n.WriteString("\n")
	}
	writeFile(dir, "non-production.md", &n)
}

func srcURLOf(cat *Catalog, id string) string {
	for _, s := range cat.Sources {
		if s.ID == id {
			return s.URL
		}
	}
	return ""
}
