package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/1a-li-lu-le-lo/trimblemcp/internal/catalog"
)

func mdEscape(s string) string {
	return strings.NewReplacer("|", "\\|", "\n", " ", "<", "&lt;", ">", "&gt;").Replace(s)
}

func counts(ops []Operation, pred func(Operation) bool) map[string]int {
	c := map[string]int{}
	for _, o := range ops {
		if pred(o) {
			c[o.Disposition]++
			c["total"]++
		}
	}
	return c
}

func writeFile(dir, name string, b *strings.Builder) {
	if err := os.WriteFile(filepath.Join(dir, name), []byte(b.String()), 0o644); err != nil {
		fail("%v", err)
	}
}

const generatedNote = "<!-- Generated by cmd/trimble-catalog from the official API definitions. Do not edit by hand; run `make catalog`. -->\n\n"

var familyTitle = map[string]string{
	"connect":        "Trimble Connect",
	"construction":   "Construction software",
	"geospatial":     "Geospatial",
	"transportation": "Transportation",
	"maps":           "Trimble Maps",
	"agriculture":    "Agriculture (PTx Trimble)",
	"identity":       "Trimble Identity",
}

func sourceLink(s *Source) string {
	return fmt.Sprintf("[%s](%s)", s.ID, s.URL)
}

func findSource(cat *Catalog, id string) *Source {
	for i := range cat.Sources {
		if cat.Sources[i].ID == id {
			return &cat.Sources[i]
		}
	}
	fail("unknown source %s", id)
	return nil
}

func apiSources(a API) []string {
	if len(a.Sources) > 0 {
		return a.Sources
	}
	return []string{a.Source}
}

func inAPI(a API) func(Operation) bool {
	srcs := map[string]bool{}
	for _, s := range apiSources(a) {
		srcs[s] = true
	}
	return func(o Operation) bool { return srcs[o.Source] }
}

func writeDocs(dir string, cat *Catalog) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		fail("%v", err)
	}
	var b strings.Builder
	b.WriteString(generatedNote)
	b.WriteString("# Trimble API endpoint coverage\n\n")
	fmt.Fprintf(&b, "Every operation in every Trimble API definition the bridge could find is listed here with exactly one disposition. The definitions were retrieved on %s from these sources:\n\n", cat.Retrieved)
	fmt.Fprintf(&b, "- the official Trimble-Connect SwaggerHub organisation (%s);\n", cat.Index)
	fmt.Fprintf(&b, "- every OpenAPI definition embedded in a Trimble Developer Portal (%s) reference page, found by crawling each product section's sitemap;\n", cat.Portal)
	b.WriteString("- definitions that Trimble products publish directly, and Vista's per-operation definitions;\n")
	b.WriteString("- the Trimble Identity OpenID Connect discovery document.\n\n")
	b.WriteString("`internal/catalog` tests fail if any operation lacks a disposition, and the generator fails on any definition it cannot classify. Products that publish no machine-readable definition are accounted for in [../capability-matrix.md](../capability-matrix.md).\n\n")
	b.WriteString("| Disposition | Meaning | MCP tool |\n|---|---|---|\n")
	b.WriteString("| `read` | Trimble Connect production read; executed against the documented regional host | `trimble_api_read`, or a typed tool where listed |\n")
	b.WriteString("| `plan` | Trimble Connect production change (POST, PUT, PATCH or DELETE); validated and returned as a dry-run request plan, never executed | `trimble_api_plan` |\n")
	b.WriteString("| `reference` | Another Trimble product's documented operation. Searchable, and can be validated into a dry-run request plan; never executed, because the bridge holds no credentials or host for that product | `trimble_api_operations`, `trimble_api_plan` |\n")
	b.WriteString("| `variant` | The same call as the operation named in `covered_by`: a staging, integration, QA, test or draft copy, or a second module publishing the same endpoint | Use the `covered_by` operation |\n")
	b.WriteString("| `excluded` | Not callable by the bridge; the reason is recorded per operation | none |\n\n")

	all := counts(cat.Operations, func(Operation) bool { return true })
	fmt.Fprintf(&b, "**Totals:** %d operations in %d definitions; %d read, %d plan, %d reference, %d variant, %d excluded.\n\n",
		all["total"], len(cat.Sources), all["read"], all["plan"], all["reference"], all["variant"], all["excluded"])

	b.WriteString("## Trimble Connect APIs (executable reads)\n\n| API | Status | Definition | Regions | Operations | read | plan | excluded | Reference |\n|---|---|---|---|---|---|---|---|---|\n")
	for _, a := range cat.APIs {
		if a.Kind != catalog.KindConnect {
			continue
		}
		c := counts(cat.Operations, inAPI(a))
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %d | %d | %d | %d | [%s.md](%s.md) |\n",
			a.Title, a.Status, sourceLink(findSource(cat, a.Source)), strings.Join(a.Regions, ", "), c["total"], c["read"], c["plan"], c["excluded"], a.ID, a.ID)
	}

	b.WriteString("\n## Other Trimble products (reference)\n\nThese operations are catalogued from the products' own published definitions so that agents can find them, read their parameters and prepare a validated dry-run plan. The bridge never calls these products: it has no credentials for them, and several are single-tenant or on-premises with a customer-specific host. Each API page states the authentication and what a deployment would need.\n\n")
	families := map[string][]API{}
	var fams []string
	for _, a := range cat.APIs {
		if a.Kind != catalog.KindReference {
			continue
		}
		if families[a.Family] == nil {
			fams = append(fams, a.Family)
		}
		families[a.Family] = append(families[a.Family], a)
	}
	sort.Strings(fams)
	for _, f := range fams {
		fmt.Fprintf(&b, "### %s\n\n| API | Product | Definitions | Operations | Authentication | Reference |\n|---|---|---|---|---|---|\n", firstNonEmpty(familyTitle[f], f))
		for _, a := range families[f] {
			c := counts(cat.Operations, inAPI(a))
			defs := fmt.Sprint(len(apiSources(a)))
			if len(apiSources(a)) == 1 {
				defs = sourceLink(findSource(cat, a.Source))
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %d | %s | [%s.md](%s.md) |\n", a.ID, mdEscape(a.Title), defs, c["total"], mdEscape(a.Auth), a.ID, a.ID)
		}
		b.WriteString("\n")
	}

	b.WriteString("## All definitions\n\n| Definition | Title | Kind | Class | API | Operations | Note |\n|---|---|---|---|---|---|---|\n")
	for i := range cat.Sources {
		s := &cat.Sources[i]
		note := s.Note
		if s.VariantOf != "" {
			note = "variant of " + s.VariantOf + "; " + note
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %d | %s |\n", sourceLink(s), mdEscape(s.Title), s.Kind, s.Class, s.API, s.Ops, mdEscape(note))
	}
	b.WriteString("\nNon-production, excluded and Trimble Identity operations are listed in [non-production.md](non-production.md).\n\n")

	b.WriteString("## Trimble Connect services without a definition\n\nThe Trimble Connect `GET /tc/api/2.0/regions` response names these services, but Trimble publishes no API definition for them, so they have no catalogued operations and the bridge does not call them.\n\n| Service | Note |\n|---|---|\n")
	for _, s := range cat.Undefined {
		fmt.Fprintf(&b, "| `%s` | %s |\n", s.Name, mdEscape(s.Note))
	}

	b.WriteString("\n## Hosts\n\nTrimble Connect base URLs are taken from each definition's `servers` block and cross-checked against `GET https://app.connect.trimble.com/tc/api/2.0/regions`. Core API paths that do not start with `/2.x/` are served under `/tc/api/2.0`. Reference APIs list their documented servers on their own pages.\n\n")
	for _, a := range cat.APIs {
		if a.Kind != catalog.KindConnect {
			continue
		}
		fmt.Fprintf(&b, "- **%s**:", a.ID)
		for _, env := range []string{"production", "stage"} {
			hs := a.Hosts[env]
			if len(hs) == 0 {
				continue
			}
			var rs []string
			for r := range hs {
				rs = append(rs, r)
			}
			sort.Strings(rs)
			var parts []string
			for _, r := range rs {
				parts = append(parts, r+" `"+hs[r]+"`")
			}
			fmt.Fprintf(&b, " %s: %s.", env, strings.Join(parts, ", "))
		}
		b.WriteString("\n")
	}
	writeFile(dir, "README.md", &b)

	for _, a := range cat.APIs {
		writeAPIDoc(dir, cat, a)
	}
	writeNonProduction(dir, cat)
}

func writeAPIDoc(dir string, cat *Catalog, a API) {
	var p strings.Builder
	p.WriteString(generatedNote)
	fmt.Fprintf(&p, "# %s\n\n", a.Title)
	sec := strings.Join(a.Security, ", ")
	if sec == "" {
		sec = "none declared"
	}
	if a.Kind == catalog.KindConnect {
		fmt.Fprintf(&p, "- **Definition:** %s, status %s. Security schemes: %s.\n", sourceLink(findSource(cat, a.Source)), a.Status, sec)
		if s := findSource(cat, a.Source); len(s.DocURLs) > 0 {
			fmt.Fprintf(&p, "- **Developer Portal:** %s.\n", strings.Join(s.DocURLs, ", "))
		}
		fmt.Fprintf(&p, "- **Regions:** %s.\n", strings.Join(a.Regions, ", "))
		p.WriteString("- **Calling from the MCP:** pass the operation `key` (`" + a.ID + ":METHOD path`) to `trimble_api_read` (read) or `trimble_api_plan` (plan), with `product: \"trimble-connect\"`. Path, query and header parameters are validated against this catalogue.\n\n")
	} else {
		fmt.Fprintf(&p, "- **Product:** %s (%s family).\n", mdEscape(a.Product), firstNonEmpty(familyTitle[a.Family], a.Family))
		fmt.Fprintf(&p, "- **Disposition:** `reference`. The bridge never calls this API; operations can be searched with `trimble_api_operations` and validated into a dry-run plan with `trimble_api_plan` (omit `product`).\n")
		fmt.Fprintf(&p, "- **Authentication:** %s. Declared security schemes: %s.\n", mdEscape(a.Auth), sec)
		fmt.Fprintf(&p, "- **Access:** %s.\n", mdEscape(a.Access))
		fmt.Fprintf(&p, "- **To call it you would need:** %s.\n", mdEscape(a.Requires))
		if len(a.Servers) > 0 {
			var sv []string
			for _, s := range a.Servers {
				sv = append(sv, "`"+s+"`"+serverNote(s))
			}
			fmt.Fprintf(&p, "- **Documented servers:** %s.\n", strings.Join(sv, ", "))
		} else {
			p.WriteString("- **Documented servers:** none in the definition.\n")
		}
		if len(apiSources(a)) == 1 {
			s := findSource(cat, a.Source)
			fmt.Fprintf(&p, "- **Definition:** %s (%s, version %s).", sourceLink(s), mdEscape(firstNonEmpty(s.Title, a.Product)), mdEscape(s.Version))
			if len(s.DocURLs) > 0 {
				fmt.Fprintf(&p, " Documentation: %s.", strings.Join(s.DocURLs, ", "))
			}
			p.WriteString("\n")
		} else {
			fmt.Fprintf(&p, "- **Definitions:** %d, one section each below.\n", len(apiSources(a)))
		}
		p.WriteString("\n")
	}

	multi := len(apiSources(a)) > 1
	split := multi && counts(cat.Operations, inAPI(a))["total"] > splitAbove
	if split {
		p.WriteString("## Definitions\n\nThis API is large, so each definition has its own page.\n\n| Definition | Operations | Page |\n|---|---|---|\n")
	}
	for _, sid := range apiSources(a) {
		var ops []Operation
		for _, o := range cat.Operations {
			if o.Source == sid {
				ops = append(ops, o)
			}
		}
		if multi {
			s := findSource(cat, sid)
			sec := &p
			var sub strings.Builder
			if split {
				page := subPage(a.ID, sid)
				fmt.Fprintf(&p, "| %s | %d | [%s](%s) |\n", mdEscape(firstNonEmpty(s.Title, sid)), s.Ops, page, page)
				sub.WriteString(generatedNote)
				fmt.Fprintf(&sub, "# %s\n\nPart of [%s](%s.md): disposition, authentication and requirements are stated there.\n\n", mdEscape(firstNonEmpty(s.Title, sid)), mdEscape(a.Title), a.ID)
				sec = &sub
			}
			fmt.Fprintf(sec, "## %s\n\nDefinition %s, %d operations.", mdEscape(firstNonEmpty(s.Title, sid)), sourceLink(s), s.Ops)
			if len(s.DocURLs) > 0 && s.Kind != "vista" {
				fmt.Fprintf(sec, " Documentation: %s.", strings.Join(s.DocURLs, ", "))
			}
			sec.WriteString("\n\n")
			if len(ops) > 0 {
				sec.WriteString("| Method | Path | Disposition | Tag | Summary | Parameters |\n|---|---|---|---|---|---|\n")
				for _, o := range ops {
					fmt.Fprintf(sec, "| `%s` | `%s` | %s | %s | %s | %s |\n", o.Method, o.Path, dispCell(o), mdEscape(firstOr(o.Tags, "")), summaryCell(o), paramsCell(o))
				}
				sec.WriteString("\n")
			}
			if split {
				sub.WriteString("`*` marks a required parameter.\n")
				writeFile(dir, subPage(a.ID, sid), &sub)
			}
			continue
		}
		byTag := map[string][]Operation{}
		var tags []string
		for _, o := range ops {
			t := firstOr(o.Tags, "Untagged")
			if byTag[t] == nil {
				tags = append(tags, t)
			}
			byTag[t] = append(byTag[t], o)
		}
		sort.Strings(tags)
		for _, t := range tags {
			fmt.Fprintf(&p, "## %s\n\n| Method | Path | Disposition | Summary | Parameters |\n|---|---|---|---|---|\n", mdEscape(t))
			for _, o := range byTag[t] {
				fmt.Fprintf(&p, "| `%s` | `%s` | %s | %s | %s |\n", o.Method, o.Path, dispCell(o), summaryCell(o), paramsCell(o))
			}
			p.WriteString("\n")
		}
	}
	if split {
		p.WriteString("\n")
	}
	p.WriteString("`*` marks a required parameter.\n")
	writeFile(dir, a.ID+".md", &p)
}

// splitAbove is the operation count above which a multi-definition API gets
// one page per definition, keeping each page small enough to render on GitHub.
const splitAbove = 1500

// subPage names the page of one definition of a split API.
func subPage(api, source string) string {
	return api + "--" + source[strings.LastIndex(source, "/")+1:] + ".md"
}

// serverNote flags documented servers that cannot be called as written.
func serverNote(s string) string {
	switch {
	case strings.Contains(s, "{"):
		return " (template: the customer's host)"
	case !strings.Contains(s, "://"):
		return " (relative: the product's host is not stated)"
	case strings.Contains(s, "://example.com"):
		return " (placeholder in the definition)"
	case strings.Contains(s, "://localhost"), strings.Contains(s, "://127.0.0.1"):
		return " (local address)"
	}
	return ""
}

func dispCell(o Operation) string {
	d := "`" + o.Disposition + "`"
	switch {
	case o.Tool != "":
		d += " (also `" + o.Tool + "`)"
	case o.Disposition == catalog.Excluded:
		d += ": " + mdEscape(o.Reason)
	case o.CoveredBy != "":
		d += ": same call as `" + o.CoveredBy + "`"
	}
	return d
}

func summaryCell(o Operation) string {
	s := mdEscape(o.Summary)
	if o.Deprecated {
		s = "**Deprecated.** " + s
	}
	return s
}

func paramsCell(o Operation) string {
	var ps []string
	for _, pr := range o.Params {
		req := ""
		if pr.Required {
			req = "*"
		}
		ps = append(ps, fmt.Sprintf("%s%s (%s)", pr.Name, req, pr.In))
	}
	if len(o.BodyTypes) > 0 {
		ps = append(ps, "body: "+strings.Join(o.BodyTypes, ", "))
	}
	return mdEscape(strings.Join(ps, "; "))
}

func writeNonProduction(dir string, cat *Catalog) {
	var n strings.Builder
	n.WriteString(generatedNote)
	n.WriteString("# Non-production, excluded and Identity operations\n\n")
	n.WriteString("Every operation in a definition that is not a Trimble Connect production API or another product's reference API:\n\n")
	n.WriteString("- Trimble Connect staging, integration, QA, test, draft, internal or empty definitions. `variant` operations are the same call as the production operation they name; `excluded` operations exist only outside production or in Trimble-internal APIs.\n")
	n.WriteString("- Definitions that are publicly reachable but not linked from Trimble documentation, or that are placeholders. The bridge does not use undocumented endpoints.\n")
	n.WriteString("- Trimble Identity endpoints, which carry credentials and are never agent-callable.\n\n")
	for i := range cat.Sources {
		s := &cat.Sources[i]
		if s.Class == "production" || s.Class == "reference" {
			continue
		}
		fmt.Fprintf(&n, "## %s (%s)\n\n%s. %d operations. Definition: %s.\n\n", s.ID, s.Class, mdEscape(strings.TrimSuffix(firstNonEmpty(s.Note, s.Title), ".")), s.Ops, sourceLink(s))
		if s.Ops == 0 {
			continue
		}
		n.WriteString("| Method | Path | Disposition | Detail |\n|---|---|---|---|\n")
		for _, o := range cat.Operations {
			if o.Source != s.ID {
				continue
			}
			detail := o.Reason
			if o.CoveredBy != "" {
				detail = "covered by `" + o.CoveredBy + "`"
			}
			fmt.Fprintf(&n, "| `%s` | `%s` | `%s` | %s |\n", o.Method, o.Path, o.Disposition, mdEscape(detail))
		}
		n.WriteString("\n")
	}
	writeFile(dir, "non-production.md", &n)
}
